var tagTips = {
  "html/css": "5|It was 1999 when I started writing my first line of HTML, it was just table tag. That moment, I know I\'m in love with HTML.",
  "ui/ux design": "5|I used to be very proud of my design skills until a client told me that my design is cool, but NOT practical and I don\'t understand his client. I know I need more than just a GOOD and BEAUTIFUL design, and I can charge more than with even a simpler design. It was 2005.",
  "mobile-first design": "5|There are so many reasons for this. Everything I do, I will do on mobile first.",
  "wireframe": "5|I only heard the word wireframe for the first time in 2011. Then I know the sketch I usually do before starting any design are called wireframe. Lame",
  "ux flow": "5|I start doing this quite often now. It gives me so much insight about what I should do, #NoStupidDesign",
  "photoshop": "5|Say Thanks to Adobe Photoshop wouldn\'t be enough. A tool that I can make a living on it.",
  "illustrator": "I\'m familiar with most of vector progams. From CorelDraw to Illustrator. I use Adobe Illustrator for almost anything: wireframe, diagram.. ",
  "prototype": "5|I consider myself as a scientist in making prototype. To have a good product, we need to build a lot of prototype, and I\'m cool with it.",
  "shopify": "5|I had a lot of e-commerce websites built from 2000 to 2005 with osCommerce, have you heard of it? And when I heard of Shopify in 2011, I know they will be successful.",
  "uploadcare": "4|Such a good API. I got a chat with its CTO and will use it for any startup project",
  "auth0": "3|One of my favourite tool in my Serverless strategy",
  "stormpath": "3|Such a good tool to do Authentication",
  "aws ec2": "2|I can set up anything there. When it\'s not my daily job, I found it\'s not fast",
  "aws lambda": "1|I\'m a big fan of Serverless infrastructure. I've just started with it.",
  "aws cloudfront": "4|I\'m cool with this. No problem at all",
  "aws s3": "5|I would tell you how much I love this. Since I know S3, I\'ve killed all of my shared host accounts.",
  "nodejs": "3|I love node! Somebody might say this and that about Node but I still love it. Just like I used to love PHP",
  "expressjs": "3|No problem, I can do this",
  "aws elb": "2|Such a good tool for scalable websites, wish I knew it earlier. I can use it know",
  "newrelic": "2|Honestly, I don\'t use it for my daily task. Shame on me.",
  "sketchapp": "5|OK, tell you this. I use this tool for every web/mobile design since I know it. #NoMorePhotoshop",
  "cloudflare": "4|I set it up for any projects",
  "buildkite": "2|Started using it in late 2015. Continuous building is great!",
  "automation": "3|I\'m a lazy developer.",
  "gulp": "4|OMG, I gulp everything, sometimes I overuse it.",
  "continuous integration": "2|I found it\'s very productive.",
  "unit test": "3|Do it more often now, Chai/Mocha/Sinon.. I\'m cool with it",
  "rspec": "1|I\'m a newbie with acceptance testing, selenium, capybara but I start using it quite often now",
  "javascript": "5|I just use it naturally until I realise I can do everything with it.",
  "reactjs": "3|I\'ve jumped into reactJS recently, I used to be very sceptical about it as it\'s not quite an MVP model like Angular. But love it know, it\'s my first choice for any new front-end project.",
  "redux": "3|It\'s quite natural when I googled to find a library to manage state in ReactJS, then I found it. OK, I can\'t use reactJS without Redux.",
  "aws dynamodb": "1|I\'ve just started with it and really need more project to get more experience",
  "swagger": "2|Such a good tool to design the API. Cool, I can do swagger. Then what\'s next?",
  "html5": "4|OK, tell you this. I\'m so addictive to HTML5. Come on, let me do something on it. I haven\'t got much commercial experience with HTML5, but I do it on my personal projects all the time.",
  "canvas": "4|I\'m an artist, and it\'s a Canvas. You know what an artist will do with a Canvas? They make amazing creative things.",
  "framework engineering": "3|I hate to repeat myself, I make framework to avoid that. Building a framework take time, but it\'s paid off.",
  "createjs": "2|Love this library, want to do it more often. Before knowing createjs, I had been building a similar library, but haven\'t got a chance to finish it.",
  "tweenjs": "2|My farouvite stuff to do animation. #RetroFlash",
  "soundjs": "2|Not quite like it, there\'s a few bugs on iOS, I ended up using my own library",
  "preloadjs": "2|Yep, like it. Wait a second! Why do we need to preload? Why not showing it immediately. Do we really need it? #NoLoadingPlease",
  "agile": "4|People repeat it too much in my workplace.",
  "scrum": "4|Part of my work everyday",
  "mvp": "4|Eric, you saved my life on doing shit things! jQuery skill is still useful to make a quick demo",
  "responsive design": "5|It\'s not new. When I designed my first website in with TABLE tag only. I started using it width=\'*\' to make sure it always fit.",
  "azure": "2|Use it for a project. I\'m not a fan of it.",
  "balsamiq": "5|Best wireframe tool ever.",
  "google dfp": "5|Got a lot of experience doing this, working with Ad ops team to deliver better ads",
  "jquery": "5|I can do technically anything with jQuery",
  "mysql": "4|I\'m familiar with it",
  "angularjs": "4|When I get bored with Wordpress CMS, AngularJS came and become a my hero for any small projects",
  "google map api": "4|So powerful tool and I\'m good with it",
  "serverless": "2|It\'s quite natural, then I heard about it officially from serverless community. Everything I do now, I\'ll avoid building a server for it",
  "geo-location calculation": "4|It\'s like I\'m a high school student. I always have a lot of fun doing this.",
  "maxcdn": "4|I\'ve been using this for 3 years. Love it.",
  "single page app": "4|If it doesn\'t require too much SEO, It\'s always my first choice to build a web app."
}